version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    container_name: pg-local
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: wiltonn
      POSTGRES_PASSWORD: lamp4life
      POSTGRES_DB: ara_development
    volumes:
      - pg_data:/var/lib/postgresql/data
    # Uncomment to set a fixed time‑zone (optional)
    environment:
       TZ: America/Toronto

volumes:
  pg_data:
