import type { WizardConfig } from '../types/wizard';
import { SCORING_PILLARS } from '../types/wizard';

export const WIZARD_CONFIG: WizardConfig = {
  metadata: {
    title: 'Agent Readiness Audit',
    description: 'Comprehensive assessment of your organization\'s readiness for AI agent implementation',
    version: '1.0.0',
    estimatedTimeMinutes: 15,
  },
  steps: [
    {
      id: 'step_1',
      title: 'Organization Overview',
      description: 'Tell us about your organization and current technology landscape',
      order: 1,
      estimatedTimeMinutes: 3,
      questions: [
        {
          id: 'company_size',
          stepId: 'step_1',
          type: 'single_select',
          title: 'What is your organization size?',
          description: 'This helps us tailor recommendations to your scale',
          required: true,
          options: [
            { id: 'startup', label: 'Startup (1-10 employees)', value: 'startup', weight: 0.8 },
            { id: 'small', label: 'Small Business (11-50 employees)', value: 'small', weight: 0.9 },
            { id: 'medium', label: 'Medium Business (51-200 employees)', value: 'medium', weight: 1.0 },
            { id: 'large', label: 'Large Enterprise (201-1000 employees)', value: 'large', weight: 1.1 },
            { id: 'enterprise', label: 'Large Enterprise (1000+ employees)', value: 'enterprise', weight: 1.2 },
          ],
          scoring: {
            pillar: SCORING_PILLARS.BUSINESS_READINESS,
            weight: 0.2,
            scoringFunction: 'weighted',
          },
        },
        {
          id: 'industry',
          stepId: 'step_1',
          type: 'single_select',
          title: 'What industry are you in?',
          description: 'Different industries have varying AI readiness considerations',
          required: true,
          options: [
            { id: 'technology', label: 'Technology/Software', value: 'technology', weight: 1.2 },
            { id: 'finance', label: 'Financial Services', value: 'finance', weight: 1.0 },
            { id: 'healthcare', label: 'Healthcare', value: 'healthcare', weight: 0.9 },
            { id: 'retail', label: 'Retail/E-commerce', value: 'retail', weight: 1.0 },
            { id: 'manufacturing', label: 'Manufacturing', value: 'manufacturing', weight: 0.8 },
            { id: 'consulting', label: 'Consulting/Services', value: 'consulting', weight: 1.1 },
            { id: 'education', label: 'Education', value: 'education', weight: 0.9 },
            { id: 'other', label: 'Other', value: 'other', weight: 0.8 },
          ],
          scoring: {
            pillar: SCORING_PILLARS.BUSINESS_READINESS,
            weight: 0.15,
            scoringFunction: 'weighted',
          },
        },
        {
          id: 'current_ai_usage',
          stepId: 'step_1',
          type: 'single_select',
          title: 'How is your organization currently using AI?',
          required: true,
          options: [
            { id: 'none', label: 'Not using AI at all', value: 'none', weight: 0.2 },
            { id: 'exploring', label: 'Exploring/researching AI options', value: 'exploring', weight: 0.4 },
            { id: 'pilot', label: 'Running pilot AI projects', value: 'pilot', weight: 0.6 },
            { id: 'limited_production', label: 'Limited AI in production', value: 'limited_production', weight: 0.8 },
            { id: 'wide_adoption', label: 'Wide AI adoption across teams', value: 'wide_adoption', weight: 1.0 },
          ],
          scoring: {
            pillar: SCORING_PILLARS.BUSINESS_READINESS,
            weight: 0.3,
            scoringFunction: 'weighted',
          },
        },
      ],
    },
    {
      id: 'step_2',
      title: 'Technical Infrastructure',
      description: 'Assess your current technical capabilities and infrastructure',
      order: 2,
      estimatedTimeMinutes: 4,
      questions: [
        {
          id: 'tech_stack_maturity',
          stepId: 'step_2',
          type: 'scale_rating',
          title: 'How would you rate your current technology stack maturity?',
          description: 'Consider factors like modern frameworks, APIs, cloud infrastructure, and development practices',
          required: true,
          validation: {
            min: 1,
            max: 10,
          },
          scoring: {
            pillar: SCORING_PILLARS.TECHNICAL_READINESS,
            weight: 0.3,
            scoringFunction: 'linear',
          },
        },
        {
          id: 'api_architecture',
          stepId: 'step_2',
          type: 'single_select',
          title: 'What best describes your current API architecture?',
          required: true,
          options: [
            { id: 'none', label: 'No APIs or very basic', value: 'none', weight: 0.2 },
            { id: 'rest_basic', label: 'Basic REST APIs', value: 'rest_basic', weight: 0.6 },
            { id: 'rest_mature', label: 'Mature REST with documentation', value: 'rest_mature', weight: 0.8 },
            { id: 'graphql', label: 'GraphQL or advanced API patterns', value: 'graphql', weight: 1.0 },
            { id: 'microservices', label: 'Microservices architecture', value: 'microservices', weight: 1.2 },
          ],
          scoring: {
            pillar: SCORING_PILLARS.TECHNICAL_READINESS,
            weight: 0.25,
            scoringFunction: 'weighted',
          },
        },
        {
          id: 'cloud_infrastructure',
          stepId: 'step_2',
          type: 'single_select',
          title: 'What is your current cloud infrastructure setup?',
          required: true,
          options: [
            { id: 'on_premise', label: 'Primarily on-premise', value: 'on_premise', weight: 0.4 },
            { id: 'hybrid', label: 'Hybrid cloud setup', value: 'hybrid', weight: 0.7 },
            { id: 'cloud_basic', label: 'Basic cloud services (IaaS)', value: 'cloud_basic', weight: 0.8 },
            { id: 'cloud_managed', label: 'Managed cloud services (PaaS)', value: 'cloud_managed', weight: 1.0 },
            { id: 'cloud_native', label: 'Cloud-native architecture', value: 'cloud_native', weight: 1.2 },
          ],
          scoring: {
            pillar: SCORING_PILLARS.TECHNICAL_READINESS,
            weight: 0.2,
            scoringFunction: 'weighted',
          },
        },
        {
          id: 'data_infrastructure',
          stepId: 'step_2',
          type: 'single_select',
          title: 'How would you describe your data infrastructure?',
          required: true,
          options: [
            { id: 'basic_db', label: 'Basic database setup', value: 'basic_db', weight: 0.3 },
            { id: 'structured_data', label: 'Well-structured data with analytics', value: 'structured_data', weight: 0.6 },
            { id: 'data_warehouse', label: 'Data warehouse/lake setup', value: 'data_warehouse', weight: 0.8 },
            { id: 'real_time', label: 'Real-time data processing capabilities', value: 'real_time', weight: 1.0 },
            { id: 'ml_ready', label: 'ML/AI-ready data infrastructure', value: 'ml_ready', weight: 1.2 },
          ],
          scoring: {
            pillar: SCORING_PILLARS.TECHNICAL_READINESS,
            weight: 0.25,
            scoringFunction: 'weighted',
          },
        },
      ],
    },
    {
      id: 'step_3',
      title: 'Development Practices',
      description: 'Evaluate your development workflows and quality processes',
      order: 3,
      estimatedTimeMinutes: 3,
      questions: [
        {
          id: 'version_control',
          stepId: 'step_3',
          type: 'single_select',
          title: 'What version control and development practices do you use?',
          required: true,
          options: [
            { id: 'basic_git', label: 'Basic Git usage', value: 'basic_git', weight: 0.6 },
            { id: 'git_workflow', label: 'Git with branching workflows', value: 'git_workflow', weight: 0.8 },
            { id: 'git_ci', label: 'Git with CI/CD pipelines', value: 'git_ci', weight: 1.0 },
            { id: 'advanced_devops', label: 'Advanced DevOps practices', value: 'advanced_devops', weight: 1.2 },
          ],
          scoring: {
            pillar: SCORING_PILLARS.TECHNICAL_READINESS,
            weight: 0.2,
            scoringFunction: 'weighted',
          },
        },
        {
          id: 'testing_practices',
          stepId: 'step_3',
          type: 'multi_select',
          title: 'What testing practices does your team follow?',
          description: 'Select all that apply',
          required: true,
          options: [
            { id: 'unit_tests', label: 'Unit testing', value: 'unit_tests', weight: 0.25 },
            { id: 'integration_tests', label: 'Integration testing', value: 'integration_tests', weight: 0.25 },
            { id: 'e2e_tests', label: 'End-to-end testing', value: 'e2e_tests', weight: 0.25 },
            { id: 'performance_tests', label: 'Performance testing', value: 'performance_tests', weight: 0.15 },
            { id: 'security_tests', label: 'Security testing', value: 'security_tests', weight: 0.1 },
          ],
          scoring: {
            pillar: SCORING_PILLARS.TECHNICAL_READINESS,
            weight: 0.15,
            scoringFunction: 'weighted',
          },
        },
        {
          id: 'code_quality',
          stepId: 'step_3',
          type: 'scale_rating',
          title: 'How would you rate your code quality and review processes?',
          description: 'Consider code reviews, linting, documentation, and maintainability',
          required: true,
          validation: {
            min: 1,
            max: 10,
          },
          scoring: {
            pillar: SCORING_PILLARS.TECHNICAL_READINESS,
            weight: 0.15,
            scoringFunction: 'linear',
          },
        },
      ],
    },
    {
      id: 'step_4',
      title: 'Security & Compliance',
      description: 'Assess your security posture and compliance requirements',
      order: 4,
      estimatedTimeMinutes: 3,
      questions: [
        {
          id: 'security_practices',
          stepId: 'step_4',
          type: 'multi_select',
          title: 'Which security practices are currently implemented?',
          description: 'Select all that apply',
          required: true,
          options: [
            { id: 'access_control', label: 'Role-based access control', value: 'access_control', weight: 0.2 },
            { id: 'encryption', label: 'Data encryption (at rest and in transit)', value: 'encryption', weight: 0.2 },
            { id: 'audit_logs', label: 'Comprehensive audit logging', value: 'audit_logs', weight: 0.15 },
            { id: 'vulnerability_scanning', label: 'Regular vulnerability scanning', value: 'vulnerability_scanning', weight: 0.15 },
            { id: 'incident_response', label: 'Incident response procedures', value: 'incident_response', weight: 0.15 },
            { id: 'security_training', label: 'Security awareness training', value: 'security_training', weight: 0.15 },
          ],
          scoring: {
            pillar: SCORING_PILLARS.SECURITY_READINESS,
            weight: 0.4,
            scoringFunction: 'weighted',
          },
        },
        {
          id: 'compliance_requirements',
          stepId: 'step_4',
          type: 'multi_select',
          title: 'What compliance requirements do you need to meet?',
          description: 'Select all that apply',
          required: false,
          options: [
            { id: 'gdpr', label: 'GDPR', value: 'gdpr', weight: 0.2 },
            { id: 'hipaa', label: 'HIPAA', value: 'hipaa', weight: 0.2 },
            { id: 'sox', label: 'SOX', value: 'sox', weight: 0.2 },
            { id: 'iso27001', label: 'ISO 27001', value: 'iso27001', weight: 0.2 },
            { id: 'pci_dss', label: 'PCI DSS', value: 'pci_dss', weight: 0.2 },
            { id: 'none', label: 'No specific compliance requirements', value: 'none', weight: 0 },
          ],
          scoring: {
            pillar: SCORING_PILLARS.SECURITY_READINESS,
            weight: 0.3,
            scoringFunction: 'weighted',
          },
        },
        {
          id: 'data_sensitivity',
          stepId: 'step_4',
          type: 'single_select',
          title: 'How sensitive is the data your organization handles?',
          required: true,
          options: [
            { id: 'public', label: 'Mostly public data', value: 'public', weight: 1.0 },
            { id: 'internal', label: 'Internal business data', value: 'internal', weight: 0.8 },
            { id: 'confidential', label: 'Confidential customer data', value: 'confidential', weight: 0.6 },
            { id: 'regulated', label: 'Highly regulated data (PII, financial, health)', value: 'regulated', weight: 0.4 },
          ],
          scoring: {
            pillar: SCORING_PILLARS.SECURITY_READINESS,
            weight: 0.3,
            scoringFunction: 'weighted',
          },
        },
      ],
    },
    {
      id: 'step_5',
      title: 'Operations & Monitoring',
      description: 'Evaluate your operational capabilities and monitoring setup',
      order: 5,
      estimatedTimeMinutes: 2,
      questions: [
        {
          id: 'monitoring_capabilities',
          stepId: 'step_5',
          type: 'multi_select',
          title: 'What monitoring and observability tools do you have in place?',
          description: 'Select all that apply',
          required: true,
          options: [
            { id: 'application_monitoring', label: 'Application performance monitoring', value: 'application_monitoring', weight: 0.25 },
            { id: 'infrastructure_monitoring', label: 'Infrastructure monitoring', value: 'infrastructure_monitoring', weight: 0.25 },
            { id: 'log_aggregation', label: 'Centralized logging', value: 'log_aggregation', weight: 0.2 },
            { id: 'alerting', label: 'Automated alerting', value: 'alerting', weight: 0.15 },
            { id: 'distributed_tracing', label: 'Distributed tracing', value: 'distributed_tracing', weight: 0.15 },
          ],
          scoring: {
            pillar: SCORING_PILLARS.OPERATIONAL_READINESS,
            weight: 0.4,
            scoringFunction: 'weighted',
          },
        },
        {
          id: 'deployment_automation',
          stepId: 'step_5',
          type: 'single_select',
          title: 'How automated are your deployment processes?',
          required: true,
          options: [
            { id: 'manual', label: 'Mostly manual deployments', value: 'manual', weight: 0.2 },
            { id: 'scripted', label: 'Scripted deployments', value: 'scripted', weight: 0.5 },
            { id: 'ci_cd_basic', label: 'Basic CI/CD pipelines', value: 'ci_cd_basic', weight: 0.8 },
            { id: 'ci_cd_advanced', label: 'Advanced CI/CD with testing', value: 'ci_cd_advanced', weight: 1.0 },
            { id: 'gitops', label: 'GitOps or infrastructure as code', value: 'gitops', weight: 1.2 },
          ],
          scoring: {
            pillar: SCORING_PILLARS.OPERATIONAL_READINESS,
            weight: 0.3,
            scoringFunction: 'weighted',
          },
        },
        {
          id: 'incident_response',
          stepId: 'step_5',
          type: 'scale_rating',
          title: 'How effective is your incident response and recovery process?',
          description: 'Consider detection time, response procedures, and recovery capabilities',
          required: true,
          validation: {
            min: 1,
            max: 10,
          },
          scoring: {
            pillar: SCORING_PILLARS.OPERATIONAL_READINESS,
            weight: 0.3,
            scoringFunction: 'linear',
          },
        },
      ],
    },
  ],
};